### ISSUE TITLE
Installations error with Python 3.4 (Windows)

### ISSUE THREAD

**Issue by jmozmoz** [jjgomera/iapws#10]
If I try to install iapws with the command 
```
pip install iapws 
```
using Python 3.4 on Windows:
```
>python -V
Python 3.4.3
```
I get the following error message:
```
Collecting iapws
  Using cached iapws-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-build-0m244txa\iapws\setup.py", line 7, in <module>
        long_description = file.read()
      File "C:\opt\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4975: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\xxx\AppData\Local\Temp\pip-build-0m244txa\iapws
```

**Comment by jmozmoz** [comment]
Installing on Linux works with Python 3.4.2.

**Comment by jmozmoz** [comment]
Another information: If I install it from the source, it seems to work (instead of using pip to download it from pypi):
```
> python setup.py sdist
> pip install dist\iapws-1.1.1.zip
Processing c:\gemeinsame dokumente\workspace\iapwspy\dist\iapws-1.1.1.zip
Requirement already satisfied (use --upgrade to upgrade): scipy in c:\opt\python34\lib\site-packages (from iapws==1.1.1)
Installing collected packages: iapws
  Running setup.py install for iapws
Successfully installed iapws-1.1.1
```

**Comment by jjgomera** [comment]
You are right, the version in pip don't have the last pull request from spontarelliam to solve this bug. Use the last commit in github.
